<?
	/**
	 * This file includes all PHP generated by the build script
	 * @package Basetheme
	 */

	 // Shortcodes
	require_once('sc.php');

	// PCP
	ob_start();
	require_once('pcp.php');
	ob_end_clean();
?>
